"""Standalone definition of one optimized central SRN2 Voderberg tile.

This file contains only the central piece. It specifies the numerical free
variables and reconstructs every contour vertex from them in cyclic order.
The final vertex is connected back to vertex 0; the first vertex is P1.

The decimal literals use 17 significant digits, enough to round-trip the
binary64 values generated by the optimizer. No project module, NumPy package,
or external solver is required.
"""

from __future__ import annotations

import json
from math import cos, sin

FORMAT = "voderberg-srn2-central-piece-standalone-v2"
METADATA = json.loads('{"exact_shell_thickness": 0.06542855215252787}')
ANGLE_UNIT = "radian"

# Independent degrees of freedom of the optimized central tile.
THETA = 0.31755990173132265
X = (
    (0.00067995065525965244, -0.00031651586049237149),
    (0.27071110398760467, -0.13174705346985274),
    (0.43537745611806677, -0.29134210885373563),
    (0.63696678190267031, -0.48742711801470062),
    (0.73527883319925513, -0.67441058879716076),
    (0.39537812853945159, -1.1321755098028286),
    (0.50467484986017597, -1.2608879214023965),
)
P = (
    (0.68408695264183494, -1.139283659785304),
    (0.75985575958392571, -1.0823006429214699),
    (0.83850888524869349, -1.0267954921790514),
)
Q = (
    (0.88826091250176886, -1.0725071583158279),
    (0.88898099818772924, -1.0738239688216036),
    (0.88971577521482303, -1.07515653224311),
)
Y = (
    (0.4932868028740619, -1.3549148129236628),
    (0.2542503479631823, -1.0734163691382463),
    (0.021237951533362404, -0.93133039441790488),
)
B = (-0.21456188357306991, -0.87614652573719043)

# Fixed poles. The cyclic contour starts at P1, reaches P0 along the right
# interface, and returns from P0 to P1 along the left interface.
P1 = (0.0, 1.0)
P0 = (0.0, -1.0)


def add(a, b):
    return (a[0] + b[0], a[1] + b[1])


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1])


def neg(a):
    return (-a[0], -a[1])


def rotate_point(point, angle, center):
    """Rotate a point around a center by an angle in radians."""

    c = cos(angle)
    s = sin(angle)
    relative = sub(point, center)
    return add(
        center,
        (
            c * relative[0] - s * relative[1],
            s * relative[0] + c * relative[1],
        ),
    )


def translate(points, vector):
    return tuple(add(point, vector) for point in points)


def rotate_points(points, angle, center):
    return tuple(rotate_point(point, angle, center) for point in points)


def reverse(points):
    return tuple(reversed(points))


def half_turn(points):
    """Apply the central symmetry p -> -p around the pole midpoint."""

    return tuple(neg(point) for point in points)


def concatenate(*parts):
    return tuple(point for part in parts for point in part)


def indexed_labels(prefix, count):
    return tuple(f"{prefix}[{index}]" for index in range(count))


def build_named_geometry():
    """Build every intermediate point chain used by the central contour."""

    theta = THETA
    x, p, q, y, b = X, P, Q, Y, B
    p1, p0 = P1, P0

    # A = rotation of P0 around P1, followed by translation P0-B.
    a = add(rotate_point(p0, theta, p1), sub(p0, b))

    # P_MAPPED and Q_MAPPED are the images under translation A -> B. The
    # reversal is part of the prescribed contour orientation.
    p_mapped = reverse(translate(p, sub(b, a)))
    q_mapped = reverse(translate(q, sub(b, a)))

    q_mapped_180 = half_turn(reverse(q_mapped))
    y_180 = half_turn(reverse(y))
    q_180 = half_turn(reverse(q))
    a_180 = neg(a)
    p_180 = half_turn(reverse(p))
    x_180 = half_turn(reverse(x))
    p_mapped_180 = half_turn(reverse(p_mapped))
    b_180 = neg(b)

    right_chain_used_by_left = concatenate(
        q_mapped_180,
        y_180,
        q_180,
        (a_180,),
        p_180,
        x_180,
        x,
        p,
    )
    right_chain_after_a = concatenate(q, y, q_mapped, (b,), p_mapped)
    main_right = concatenate(
        p_mapped_180,
        (b_180,),
        right_chain_used_by_left,
        (a,),
        right_chain_after_a,
    )

    # The left interface is the image of RIGHT_CHAIN_USED_BY_LEFT under a
    # rotation -THETA around B_180 followed by translation B_180 -> P1.
    main_left = translate(
        rotate_points(right_chain_used_by_left, -theta, b_180),
        sub(p1, b_180),
    )

    right_chain_labels = concatenate(
        indexed_labels("Q_MAPPED_180", len(q_mapped_180)),
        indexed_labels("Y_180", len(y_180)),
        indexed_labels("Q_180", len(q_180)),
        ("A_180",),
        indexed_labels("P_180", len(p_180)),
        indexed_labels("X_180", len(x_180)),
        indexed_labels("X", len(x)),
        indexed_labels("P", len(p)),
    )
    right_after_a_labels = concatenate(
        indexed_labels("Q", len(q)),
        indexed_labels("Y", len(y)),
        indexed_labels("Q_MAPPED", len(q_mapped)),
        ("B",),
        indexed_labels("P_MAPPED", len(p_mapped)),
    )
    main_right_labels = concatenate(
        indexed_labels("P_MAPPED_180", len(p_mapped_180)),
        ("B_180",),
        right_chain_labels,
        ("A",),
        right_after_a_labels,
    )
    main_left_labels = tuple(f"LEFT_IMAGE({label})" for label in right_chain_labels)

    return {
        "A": a,
        "A_180": a_180,
        "B_180": b_180,
        "P_MAPPED": p_mapped,
        "Q_MAPPED": q_mapped,
        "P_MAPPED_180": p_mapped_180,
        "Q_MAPPED_180": q_mapped_180,
        "P_180": p_180,
        "Q_180": q_180,
        "X_180": x_180,
        "Y_180": y_180,
        "RIGHT_CHAIN_USED_BY_LEFT": right_chain_used_by_left,
        "RIGHT_CHAIN_AFTER_A": right_chain_after_a,
        "MAIN_RIGHT": main_right,
        "MAIN_LEFT": main_left,
        "MAIN_RIGHT_LABELS": main_right_labels,
        "MAIN_LEFT_LABELS": main_left_labels,
    }


def build_central_contour():
    """Return the cyclically ordered contour vertices of the central piece."""

    geometry = build_named_geometry()
    return concatenate(
        (P1,),
        geometry["MAIN_RIGHT"],
        (P0,),
        reverse(geometry["MAIN_LEFT"]),
    )


def build_contour_labels():
    """Return one construction label for every ordered contour vertex."""

    geometry = build_named_geometry()
    return concatenate(
        ("P1",),
        geometry["MAIN_RIGHT_LABELS"],
        ("P0",),
        reverse(geometry["MAIN_LEFT_LABELS"]),
    )


def build_piece_definition():
    """Return the complete standalone report for the central polygon."""

    contour = build_central_contour()
    labels = build_contour_labels()
    if len(contour) != len(labels):
        raise RuntimeError("Point-label count does not match contour length.")

    point_records = tuple(
        {"index": index, "label": label, "coordinates": point}
        for index, (label, point) in enumerate(zip(labels, contour))
    )
    cyclic_edges = tuple((index, (index + 1) % len(contour)) for index in range(len(contour)))

    return {
        "format": FORMAT,
        "metadata": METADATA,
        "angle_unit": ANGLE_UNIT,
        "free_variables": {
            "theta": THETA,
            "X": X,
            "P": P,
            "Q": Q,
            "Y": Y,
            "B": B,
        },
        "central_piece": {
            "cyclic": True,
            "start_vertex": "P1",
            "closure": "The last point is connected to point 0.",
            "point_count": len(contour),
            "ordered_points": contour,
            "point_labels": labels,
            "point_records": point_records,
            "cyclic_edges": cyclic_edges,
        },
    }


def _json_compatible(value):
    if isinstance(value, dict):
        return {key: _json_compatible(item) for key, item in value.items()}
    if isinstance(value, tuple):
        return [_json_compatible(item) for item in value]
    return value


if __name__ == "__main__":
    print(json.dumps(_json_compatible(build_piece_definition()), indent=2, sort_keys=True))
