"""Standalone reports for the optimized central SRN2 tile.

The generated Python file depends only on the Python standard library. It
contains the free variables at full binary64 round-trip precision and the exact
ordered construction used to obtain the cyclic contour of the central piece.
Copies of the tile and shell-only geometry deliberately do not belong to this
report; they remain visualization and validation artifacts of the main project.
"""

from __future__ import annotations

import json
from pathlib import Path
from textwrap import dedent
from typing import Any

import numpy as np

from .state import SRN2State
from .topology import TileAssembly


def _float_literal(value: Any) -> str:
    """Return a decimal literal that round-trips an IEEE-754 double."""

    return format(float(value), ".17g")


def _point_literal(point: Any) -> str:
    values = np.asarray(point, dtype=float)
    return f"({_float_literal(values[0])}, {_float_literal(values[1])})"


def _chain_literal(points: Any) -> str:
    rows = np.asarray(points, dtype=float)
    if len(rows) == 1:
        return f"({_point_literal(rows[0])},)"
    return "(\n" + "\n".join(f"    {_point_literal(point)}," for point in rows) + "\n)"


def _points_as_lists(points: Any) -> list[list[float]]:
    return np.asarray(points, dtype=float).tolist()


def _central_point_labels(state: SRN2State) -> list[str]:
    """Return labels matching the exact ordered central-contour construction."""

    normalized = state.with_normalized_theta()
    p_count = len(normalized.p)
    q_count = len(normalized.q)
    x_count = len(normalized.x)
    y_count = len(normalized.y)

    right_chain_labels = (
        [f"Q_MAPPED_180[{index}]" for index in range(q_count)]
        + [f"Y_180[{index}]" for index in range(y_count)]
        + [f"Q_180[{index}]" for index in range(q_count)]
        + ["A_180"]
        + [f"P_180[{index}]" for index in range(p_count)]
        + [f"X_180[{index}]" for index in range(x_count)]
        + [f"X[{index}]" for index in range(x_count)]
        + [f"P[{index}]" for index in range(p_count)]
    )
    right_after_a_labels = (
        [f"Q[{index}]" for index in range(q_count)]
        + [f"Y[{index}]" for index in range(y_count)]
        + [f"Q_MAPPED[{index}]" for index in range(q_count)]
        + ["B"]
        + [f"P_MAPPED[{index}]" for index in range(p_count)]
    )
    main_right_labels = (
        [f"P_MAPPED_180[{index}]" for index in range(p_count)]
        + ["B_180"]
        + right_chain_labels
        + ["A"]
        + right_after_a_labels
    )
    main_left_labels = [f"LEFT_IMAGE({label})" for label in right_chain_labels]
    return ["P1"] + main_right_labels + ["P0"] + list(reversed(main_left_labels))


def _standalone_source(state: SRN2State, metadata: dict[str, Any]) -> str:
    """Create a standalone Python 3 definition of the central tile only."""

    normalized = state.with_normalized_theta()
    metadata_json = json.dumps(metadata, ensure_ascii=False, sort_keys=True)
    template = f'''\
"""Standalone definition of one optimized central SRN2 Voderberg tile.

This file contains only the central piece. It specifies the numerical free
variables and reconstructs every contour vertex from them in cyclic order.
The final vertex is connected back to vertex 0; the first vertex is P1.

The decimal literals use 17 significant digits, enough to round-trip the
binary64 values generated by the optimizer. No project module, NumPy package,
or external solver is required.
"""

from __future__ import annotations

import json
from math import cos, sin

FORMAT = "voderberg-srn2-central-piece-standalone-v2"
METADATA = json.loads({metadata_json!r})
ANGLE_UNIT = "radian"

# Independent degrees of freedom of the optimized central tile.
THETA = {_float_literal(normalized.theta)}
X = {_chain_literal(normalized.x)}
P = {_chain_literal(normalized.p)}
Q = {_chain_literal(normalized.q)}
Y = {_chain_literal(normalized.y)}
B = {_point_literal(normalized.b)}

# Fixed poles. The cyclic contour starts at P1, reaches P0 along the right
# interface, and returns from P0 to P1 along the left interface.
P1 = (0.0, 1.0)
P0 = (0.0, -1.0)


def add(a, b):
    return (a[0] + b[0], a[1] + b[1])


def sub(a, b):
    return (a[0] - b[0], a[1] - b[1])


def neg(a):
    return (-a[0], -a[1])


def rotate_point(point, angle, center):
    """Rotate a point around a center by an angle in radians."""

    c = cos(angle)
    s = sin(angle)
    relative = sub(point, center)
    return add(
        center,
        (
            c * relative[0] - s * relative[1],
            s * relative[0] + c * relative[1],
        ),
    )


def translate(points, vector):
    return tuple(add(point, vector) for point in points)


def rotate_points(points, angle, center):
    return tuple(rotate_point(point, angle, center) for point in points)


def reverse(points):
    return tuple(reversed(points))


def half_turn(points):
    """Apply the central symmetry p -> -p around the pole midpoint."""

    return tuple(neg(point) for point in points)


def concatenate(*parts):
    return tuple(point for part in parts for point in part)


def indexed_labels(prefix, count):
    return tuple(f"{{prefix}}[{{index}}]" for index in range(count))


def build_named_geometry():
    """Build every intermediate point chain used by the central contour."""

    theta = THETA
    x, p, q, y, b = X, P, Q, Y, B
    p1, p0 = P1, P0

    # A = rotation of P0 around P1, followed by translation P0-B.
    a = add(rotate_point(p0, theta, p1), sub(p0, b))

    # P_MAPPED and Q_MAPPED are the images under translation A -> B. The
    # reversal is part of the prescribed contour orientation.
    p_mapped = reverse(translate(p, sub(b, a)))
    q_mapped = reverse(translate(q, sub(b, a)))

    q_mapped_180 = half_turn(reverse(q_mapped))
    y_180 = half_turn(reverse(y))
    q_180 = half_turn(reverse(q))
    a_180 = neg(a)
    p_180 = half_turn(reverse(p))
    x_180 = half_turn(reverse(x))
    p_mapped_180 = half_turn(reverse(p_mapped))
    b_180 = neg(b)

    right_chain_used_by_left = concatenate(
        q_mapped_180,
        y_180,
        q_180,
        (a_180,),
        p_180,
        x_180,
        x,
        p,
    )
    right_chain_after_a = concatenate(q, y, q_mapped, (b,), p_mapped)
    main_right = concatenate(
        p_mapped_180,
        (b_180,),
        right_chain_used_by_left,
        (a,),
        right_chain_after_a,
    )

    # The left interface is the image of RIGHT_CHAIN_USED_BY_LEFT under a
    # rotation -THETA around B_180 followed by translation B_180 -> P1.
    main_left = translate(
        rotate_points(right_chain_used_by_left, -theta, b_180),
        sub(p1, b_180),
    )

    right_chain_labels = concatenate(
        indexed_labels("Q_MAPPED_180", len(q_mapped_180)),
        indexed_labels("Y_180", len(y_180)),
        indexed_labels("Q_180", len(q_180)),
        ("A_180",),
        indexed_labels("P_180", len(p_180)),
        indexed_labels("X_180", len(x_180)),
        indexed_labels("X", len(x)),
        indexed_labels("P", len(p)),
    )
    right_after_a_labels = concatenate(
        indexed_labels("Q", len(q)),
        indexed_labels("Y", len(y)),
        indexed_labels("Q_MAPPED", len(q_mapped)),
        ("B",),
        indexed_labels("P_MAPPED", len(p_mapped)),
    )
    main_right_labels = concatenate(
        indexed_labels("P_MAPPED_180", len(p_mapped_180)),
        ("B_180",),
        right_chain_labels,
        ("A",),
        right_after_a_labels,
    )
    main_left_labels = tuple(f"LEFT_IMAGE({{label}})" for label in right_chain_labels)

    return {{
        "A": a,
        "A_180": a_180,
        "B_180": b_180,
        "P_MAPPED": p_mapped,
        "Q_MAPPED": q_mapped,
        "P_MAPPED_180": p_mapped_180,
        "Q_MAPPED_180": q_mapped_180,
        "P_180": p_180,
        "Q_180": q_180,
        "X_180": x_180,
        "Y_180": y_180,
        "RIGHT_CHAIN_USED_BY_LEFT": right_chain_used_by_left,
        "RIGHT_CHAIN_AFTER_A": right_chain_after_a,
        "MAIN_RIGHT": main_right,
        "MAIN_LEFT": main_left,
        "MAIN_RIGHT_LABELS": main_right_labels,
        "MAIN_LEFT_LABELS": main_left_labels,
    }}


def build_central_contour():
    """Return the cyclically ordered contour vertices of the central piece."""

    geometry = build_named_geometry()
    return concatenate(
        (P1,),
        geometry["MAIN_RIGHT"],
        (P0,),
        reverse(geometry["MAIN_LEFT"]),
    )


def build_contour_labels():
    """Return one construction label for every ordered contour vertex."""

    geometry = build_named_geometry()
    return concatenate(
        ("P1",),
        geometry["MAIN_RIGHT_LABELS"],
        ("P0",),
        reverse(geometry["MAIN_LEFT_LABELS"]),
    )


def build_piece_definition():
    """Return the complete standalone report for the central polygon."""

    contour = build_central_contour()
    labels = build_contour_labels()
    if len(contour) != len(labels):
        raise RuntimeError("Point-label count does not match contour length.")

    point_records = tuple(
        {{"index": index, "label": label, "coordinates": point}}
        for index, (label, point) in enumerate(zip(labels, contour))
    )
    cyclic_edges = tuple((index, (index + 1) % len(contour)) for index in range(len(contour)))

    return {{
        "format": FORMAT,
        "metadata": METADATA,
        "angle_unit": ANGLE_UNIT,
        "free_variables": {{
            "theta": THETA,
            "X": X,
            "P": P,
            "Q": Q,
            "Y": Y,
            "B": B,
        }},
        "central_piece": {{
            "cyclic": True,
            "start_vertex": "P1",
            "closure": "The last point is connected to point 0.",
            "point_count": len(contour),
            "ordered_points": contour,
            "point_labels": labels,
            "point_records": point_records,
            "cyclic_edges": cyclic_edges,
        }},
    }}


def _json_compatible(value):
    if isinstance(value, dict):
        return {{key: _json_compatible(item) for key, item in value.items()}}
    if isinstance(value, tuple):
        return [_json_compatible(item) for item in value]
    return value


if __name__ == "__main__":
    print(json.dumps(_json_compatible(build_piece_definition()), indent=2, sort_keys=True))
'''
    return dedent(template)


def save_standalone_solution_script(
    state: SRN2State,
    path: str | Path,
    *,
    metadata: dict[str, Any] | None = None,
) -> Path:
    """Write an executable definition of the central piece only."""

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(_standalone_source(state, metadata or {}), encoding="utf-8")
    return output


def save_solution_json(
    state: SRN2State,
    assembly: TileAssembly,
    path: str | Path,
    *,
    metadata: dict[str, Any] | None = None,
) -> Path:
    """Write a machine-readable snapshot of the central cyclic contour only."""

    normalized = state.with_normalized_theta()
    labels = _central_point_labels(normalized)
    contour = np.asarray(assembly.main_contour, dtype=float)
    if len(labels) != len(contour):
        raise ValueError("Point-label count does not match the central contour length.")

    points = _points_as_lists(contour)
    payload = {
        "format": "voderberg-srn2-central-piece-v2",
        "numerical_precision": "IEEE-754 binary64; decimal values use round-trip precision",
        "angle_unit": "radian",
        "metadata": metadata or {},
        "free_variables": {
            "theta": float(normalized.theta),
            "X": _points_as_lists(normalized.x),
            "P": _points_as_lists(normalized.p),
            "Q": _points_as_lists(normalized.q),
            "Y": _points_as_lists(normalized.y),
            "B": _points_as_lists(np.atleast_2d(normalized.b))[0],
        },
        "construction": {
            "language": "Python 3",
            "executable_definition": "See the companion standalone solution_definition.py file.",
            "scope": "central piece only",
            "contour_start": "P1",
            "contour_closure": "The last point is connected to point 0.",
            "operations": [
                "2D rotation around a specified center",
                "2D translation",
                "central symmetry p -> -p around the pole midpoint",
                "ordered chain reversal and concatenation",
            ],
        },
        "central_piece": {
            "cyclic": True,
            "point_count": len(points),
            "ordered_points": points,
            "point_labels": labels,
            "point_records": [
                {"index": index, "label": label, "coordinates": point}
                for index, (label, point) in enumerate(zip(labels, points))
            ],
            "cyclic_edges": [
                [index, (index + 1) % len(points)] for index in range(len(points))
            ],
        },
    }

    output = Path(path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    return output


__all__ = ["save_solution_json", "save_standalone_solution_script"]
